import { z } from 'zod';
import { CommentGroupId } from './comment-group-id';
import { Color } from './color';
import { zext } from '../../zext';
import { VoteCandidate } from './vote-candidate';

export const Favorite = z.object({
  title: z.string(),
  comment_group_id: CommentGroupId.zod,
  image: z.object({
    remove_yn: z.boolean(),
    urls: z.null(),
    upd_dt: z.number().int(),
    image_id: z.number().int(),
    ratio: z.number(),
    color: Color.zod,
    url: z.null(),
    path: z.string(),
  }),
  streaming_yn: z.boolean(),
  start_dt: zext.instant.epochMillis.int(),
  end_dt: zext.instant.epochMillis.int(),
  event_id: z.number().int(),
  sub_title: z.string(),
  upt_dt: zext.instant.epochMillis.int.nullIfZero(),
  vote_type: z.enum(['NORMAL']),
  ui_type: z.enum(['CHART']),
  vote_img_yn: z.boolean(),
  reward_yn: z.boolean(),
  reward_img_url: z.string().url(),
  reward_link: z.null(),
  eng_reward_yn: z.boolean(),
  eng_reward_img_url: z.string().url(),
  eng_reward_link: z.null(),
  eng_vote_img_yn: z.boolean(),
  past_reward_yn: z.boolean(),
  past_reward_img_url: z.null(),
  past_reward_img_text: z.string(),
  past_reward_link: z.null(),
  vote_use_point_type: z.enum(['ALL']),
  vote_use_point: z.number(),
  reward_img_text: z.string(),
  eng_reward_img_text: z.string(),
  vote_certificate_yn: z.boolean(),
  vote_img_text: z.string(),
  eng_vote_img_text: z.string(),
  bg_color_type: z.enum(['GREEN']),
  candidate_type: z.enum(['ARTIST']),
  comment_yn: z.boolean(),
  eng_description: z.string(),
  eng_sub_title: z.string(),
  eng_title: z.string(),
  event_img_url: z.null(),
  event_img_yn: z.boolean(),
  event_url: z.null(),
  event_yn: z.boolean(),
  vote_candidates: z.array(VoteCandidate),
  vote_info_id: z.number().int(),
  description: z.string(),
});
