on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - uses: pnpm/action-setup@v4
      - run: pnpm run crawl
      - uses: devops-infra/action-commit-push@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          add_timestamp: true
          commit_prefix: '[crawl]'
          commit_message: 'Got new bugs data'
          force: false
          target_branch: main
